import type { PlaidCategory } from "@/lib/db/schema";

// Maps Plaid Personal Finance Category (PFC) to our canonical category
// codes. Detailed-level overrides take precedence over primary-level — they
// catch the cases where the primary is too coarse (e.g. FOOD_AND_DRINK
// covers both groceries and eating out).
//
// Reference: https://plaid.com/docs/api/products/transactions/#categories-get
// Canonical codes must exist in the `category` table.

const PRIMARY_MAP: Record<string, string> = {
  INCOME: "INCOME",
  TRANSFER_IN: "TRANSFER",
  TRANSFER_OUT: "TRANSFER",
  LOAN_PAYMENTS: "FEES",
  BANK_FEES: "FEES",
  ENTERTAINMENT: "ENTERTAINMENT",
  FOOD_AND_DRINK: "EATING_OUT",
  GENERAL_MERCHANDISE: "SHOPPING",
  HOME_IMPROVEMENT: "SHOPPING",
  MEDICAL: "HEALTH",
  PERSONAL_CARE: "HEALTH",
  GENERAL_SERVICES: "OTHER",
  GOVERNMENT_AND_NON_PROFIT: "TAXES",
  TRANSPORTATION: "TRANSPORT",
  TRAVEL: "TRAVEL",
  RENT_AND_UTILITIES: "UTILITIES",
};

const DETAILED_MAP: Record<string, string> = {
  // FOOD_AND_DRINK
  FOOD_AND_DRINK_GROCERIES: "GROCERIES",
  FOOD_AND_DRINK_RESTAURANT: "EATING_OUT",
  FOOD_AND_DRINK_RESTAURANTS: "EATING_OUT",
  FOOD_AND_DRINK_FAST_FOOD: "EATING_OUT",
  FOOD_AND_DRINK_COFFEE: "EATING_OUT",
  FOOD_AND_DRINK_VENDING_MACHINES: "EATING_OUT",
  FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR: "SOCIAL",
  FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK: "EATING_OUT",

  // RENT_AND_UTILITIES
  RENT_AND_UTILITIES_RENT: "RENT",
  RENT_AND_UTILITIES_GAS_AND_ELECTRICITY: "UTILITIES",
  RENT_AND_UTILITIES_INTERNET_AND_CABLE: "UTILITIES",
  RENT_AND_UTILITIES_TELEPHONE: "UTILITIES",
  RENT_AND_UTILITIES_WATER: "UTILITIES",
  RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT: "UTILITIES",
  RENT_AND_UTILITIES_OTHER_UTILITIES: "UTILITIES",

  // ENTERTAINMENT
  ENTERTAINMENT_TV_AND_MOVIES: "SUBSCRIPTION",
  ENTERTAINMENT_MUSIC_AND_AUDIO: "SUBSCRIPTION",
  ENTERTAINMENT_VIDEO_GAMES: "ENTERTAINMENT",
  ENTERTAINMENT_CASINOS_AND_GAMBLING: "ENTERTAINMENT",
  ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS: "ENTERTAINMENT",
  ENTERTAINMENT_OTHER_ENTERTAINMENT: "ENTERTAINMENT",

  // TRANSPORTATION (primary already maps right; only edge cases)
  TRANSPORTATION_TAXIS_AND_RIDE_SHARES: "TRANSPORT",
  TRANSPORTATION_PUBLIC_TRANSIT: "TRANSPORT",
  TRANSPORTATION_GAS: "TRANSPORT",
  TRANSPORTATION_PARKING: "TRANSPORT",
  TRANSPORTATION_TOLLS: "TRANSPORT",
  TRANSPORTATION_BIKES_AND_SCOOTERS: "TRANSPORT",
  TRANSPORTATION_OTHER_TRANSPORTATION: "TRANSPORT",

  // TRAVEL
  TRAVEL_FLIGHTS: "TRAVEL",
  TRAVEL_LODGING: "TRAVEL",
  TRAVEL_RENTAL_CARS: "TRAVEL",
  TRAVEL_OTHER_TRAVEL: "TRAVEL",

  // GENERAL_SERVICES — education is the only student-relevant override
  GENERAL_SERVICES_EDUCATION: "EDUCATION",
  GENERAL_SERVICES_AUTOMOTIVE: "TRANSPORT",
  GENERAL_SERVICES_INSURANCE: "FEES",
  GENERAL_SERVICES_POSTAGE_AND_SHIPPING: "SHOPPING",
  GENERAL_SERVICES_OTHER_GENERAL_SERVICES: "OTHER",

  // GENERAL_MERCHANDISE — granular shopping breakdown maps to SHOPPING,
  // but a few cases tip elsewhere
  GENERAL_MERCHANDISE_CONVENIENCE_STORES: "GROCERIES",
  GENERAL_MERCHANDISE_SUPERSTORES: "GROCERIES", // Costco, Walmart
  GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS: "EDUCATION",
  GENERAL_MERCHANDISE_PET_SUPPLIES: "HEALTH",
  GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE: "SHOPPING",

  // MEDICAL
  MEDICAL_PHARMACIES_AND_SUPPLEMENTS: "HEALTH",
  MEDICAL_DENTAL_CARE: "HEALTH",
  MEDICAL_EYE_CARE: "HEALTH",
  MEDICAL_NURSING_CARE: "HEALTH",
  MEDICAL_PRIMARY_CARE: "HEALTH",
  MEDICAL_VETERINARY_SERVICES: "HEALTH",
  MEDICAL_OTHER_MEDICAL: "HEALTH",

  // PERSONAL_CARE
  PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS: "HEALTH",
  PERSONAL_CARE_HAIR_AND_BEAUTY: "HEALTH",
  PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING: "OTHER",
  PERSONAL_CARE_OTHER_PERSONAL_CARE: "HEALTH",

  // INCOME (primary already maps right; details inherit)
  INCOME_WAGES: "INCOME",
  INCOME_DIVIDENDS: "INCOME",
  INCOME_INTEREST_EARNED: "INCOME",
  INCOME_RETIREMENT_PENSION: "INCOME",
  INCOME_TAX_REFUND: "INCOME",
  INCOME_UNEMPLOYMENT: "INCOME",
  INCOME_OTHER_INCOME: "INCOME",

  // TRANSFER variants
  TRANSFER_IN_CASH_ADVANCES_AND_LOANS: "TRANSFER",
  TRANSFER_IN_DEPOSIT: "TRANSFER",
  TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS: "TRANSFER",
  TRANSFER_IN_SAVINGS: "TRANSFER",
  TRANSFER_IN_ACCOUNT_TRANSFER: "TRANSFER",
  TRANSFER_IN_OTHER_TRANSFER_IN: "TRANSFER",
  TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS: "TRANSFER",
  TRANSFER_OUT_SAVINGS: "TRANSFER",
  TRANSFER_OUT_WITHDRAWAL: "TRANSFER",
  TRANSFER_OUT_ACCOUNT_TRANSFER: "TRANSFER",
  TRANSFER_OUT_OTHER_TRANSFER_OUT: "TRANSFER",

  // LOAN_PAYMENTS — most are real spend, but CC payments are internal
  // transfers (the actual spending shows up as the underlying card charges
  // when the user links their credit card). Mark CC payments as TRANSFER so
  // the dashboard / engine can dedup them.
  LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT: "EDUCATION",
  LOAN_PAYMENTS_CAR_PAYMENT: "TRANSPORT",
  LOAN_PAYMENTS_MORTGAGE_PAYMENT: "RENT",
  LOAN_PAYMENTS_CREDIT_CARD_PAYMENT: "TRANSFER",
  LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT: "FEES",
  LOAN_PAYMENTS_OTHER_PAYMENT: "FEES",

  // BANK_FEES
  BANK_FEES_ATM_FEES: "FEES",
  BANK_FEES_FOREIGN_TRANSACTION_FEES: "FEES",
  BANK_FEES_INSUFFICIENT_FUNDS: "FEES",
  BANK_FEES_INTEREST_CHARGE: "FEES",
  BANK_FEES_OVERDRAFT_FEES: "FEES",
  BANK_FEES_OTHER_BANK_FEES: "FEES",

  // HOME_IMPROVEMENT (mostly shopping)
  HOME_IMPROVEMENT_FURNITURE: "SHOPPING",
  HOME_IMPROVEMENT_HARDWARE: "SHOPPING",
  HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE: "SHOPPING",
  HOME_IMPROVEMENT_SECURITY: "SHOPPING",
  HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT: "SHOPPING",

  // GOVERNMENT_AND_NON_PROFIT
  GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT: "TAXES",
  GOVERNMENT_AND_NON_PROFIT_DONATIONS: "TAXES",
  GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES: "TAXES",
  GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT: "TAXES",
};

export function toCanonical(
  pfc: PlaidCategory | null | undefined,
): string | null {
  if (!pfc) return null;
  return DETAILED_MAP[pfc.detailed] ?? PRIMARY_MAP[pfc.primary] ?? "OTHER";
}
